init.templatedir=
init.defaultbranch=main
core.editor=code --wait
user.name=Abdul Aziz
user.email=file.azis@gmail.com
credential.helper=store
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/abdaziznet/invoice-craft-app.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
